// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Thesis.Models;

public partial class DiplomnaContext : DbContext
{
    public DiplomnaContext()
    {
    }

    public DiplomnaContext(DbContextOptions<DiplomnaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Diplom> Diplom { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-HS51G25\\SQLEXPRESS;Initial Catalog=Diplomna;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Diplom>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}